version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: twistlook-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./data/dump:/docker-entrypoint-initdb.d/dump
      - ./scripts/restore-db.sh:/docker-entrypoint-initdb.d/restore-db.sh
    environment:
      - MONGO_INITDB_DATABASE=twistslook
    networks:
      - twistlook-network

volumes:
  mongodb_data:

networks:
  twistlook-network:
    driver: bridge
